name = "MyterialColors"
uuid = "1c23619d-4212-4747-83aa-717207fae70f"
authors = ["FedeClaudi <federicoclaudi@protonmail.com> and contributors"]
version = "0.1.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
