name = "MyterialColors"
uuid = "1c23619d-4212-4747-83aa-717207fae70f"
authors = ["FedeClaudi <federicoclaudi@protonmail.com> and contributors"]
version = "0.2.1"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Parameters = "0.12.3"
julia = "1.6"
Plots = "1.25.0"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
